name: flutterprojects
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.1
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  imageview360: ^1.3.0
  flutter_bounce: ^1.1.0
  flutter_zoom_drawer: ^2.0.0

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/font/
    - assets/icons/
    - assets/images/
    - assets/images/loginpage/
    - assets/images/startpages/
    - assets/logos/
    - assets/shows/
    - assets/images/addcardpageimage/
    - assets/images/appbar/
    - assets/images/profile/